### ISSUE TITLE
Add missing features on subscription detail page

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#197]
The first subscription detail page is at about 90% ready.

The following is still to be added:

- [x] ~~add Fixed inputs on General tab, and remove the placeholder text~~ --> see #279 
- [x] ~~hide Loading status~~ --> see #331 

**under configuration tab** 
- [x] ~~the product block `cards` are not shown in the same sorted order as the tree, but are added on top. Please change this that when making a product block visible it is inserted  at the right place.~~ see #282 
- [ ] ~~add a button to show all product blocks~~ see #328 
- [x] add a button to hide all product blocks
- [x] ~~add button in product block `card` to hide detail,~~ see #282
  - [x] ~~this action should hide the empty resource types, ownerSubscriptionId, Title~~ see #282
  - [x] ~~default setting of the hide button is enabled~~ see #282

**under processes tab**
- [x] ~~icons of the process is not reflecting the `create`, `modify`, `terminate` type of WF~~ see #284 
- [x] ~~add the name of the WF being run~~ see #284 

**Under the Action button**
- [x] ~~remove the create WF, it does can never be run for an existing subscription~~ --> see #278 

**Under Related subscriptions**
~~to be implemented - just as a reminder~~ see #281 

Other:
- [ ] Combine the types of SubscriptionDetail with the SubscriptionListItem. List item is basically a subset of SubscriptionDetail
- [ ] Find a way to better parse types from backend, currently type of startDate is a string but it actually is a date time as string. To discuss: maybe introduce 2 types for a Subscription: one where props like dateTime are string and one where dateTime is parsed as DateTime

**Comment by wouter1975** [comment]
@acidjunk are the last two point still current, or can this ticket be closed?
