### ISSUE TITLE
Implement task list page

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#94]
**Task list page**
Reuse the standard table component with filter/sort and table setting options.

This page is loaded when the menu item `Tasks` of the left menu is clicked. But also if the Counter Icon with failed tasks is clicked.

![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/4588e8be-978a-4369-9e31-e8a53e72c0b5)

- [x] add header
- [x] add `Rerun all` button --> no action implementation needed at this moment
- [x] add `New task` button --> no action implementation needed at this moment

**Data of table**
This table contains the same column as the Processes Table, but only the order and visible columns are different.
- [x] Processes is_task is set to True are listed under tasks
- [x] Filter the status column
  - [x] Don't show completed tasks
  - [x] Only show processes with the status `running`, `failed`, `API unavailable`, `Inconsistent data`
  - [x]  check whether these last two states exist in the orchestrator core 

Note: rerun and new-task buttons are not in scope of this story

* Load page with defaults from app, or if local storage has applicable ActiveProcessesTableSetting/CompletedProcessesTableSetting use these.
* Any column can be sorted/filtered as developed for the subscription list page https://github.com/workfloworchestrator/orchestrator-ui/issues/76 and https://github.com/workfloworchestrator/orchestrator-ui/issues/81

Default column settings and order:
assignee
last step
status
workflow --> include a link to the process detail page
target - **hidden**
tag
product - hidden
customer - hidden
abbrev - **hidden**
subscription --> include a link to the subscription detail page
creator - **hidden**
pid - hidden
started
modified

Other tasks:
- [x] Add translations
- [x] Add icons to header buttons
- [x] Avoid duplication of tableColumns in TaskList vs ProcessList (see todo in WFOTaskListPage.tsx)
- [x] Currently blocked: backend needs to match the keynames in the data with the field names in the filter (packages/orchestrator-ui-components/src/pages/tasks/WFOTaskListPage.tsx)

**Comment by wouter1975** [comment]
@ricardovdheijden looks good, I see that the spec above is missing the `Resumed` state as one of the default visible states for the task list table. I think this has been added added quite recently to V1. Can you add it?

**Comment by ricardovdheijden** [comment]
> @ricardovdheijden looks good, I see that the spec above is missing the `Resumed` state as one of the default visible states for the task list table. I think this has been added added quite recently to V1. Can you add it?

Currently it should be implemented already and has the same color as statusses:
WAITING
RUNNING
API_UNAVAILABLE
INCONSISTENT_DATA

Which is the color blue. Blue is also the default badge color in case new statusses are added in the backend
